### ISSUE TITLE
Add ability to see current config via BLE

### ISSUE THREAD

**Issue by adur1990** [gh0st42/rf95modem#7]
The `AT+INFO` command only prints to serial out, but not over BLE. Would be great to have this feature for BlueRa.

**Comment by gh0st42** [comment]
I believe that I already fixed that bug last week in the [wifi_test branch](https://github.com/gh0st42/rf95modem/tree/wifi_test)
Does this work for you? 

This will get merged into the master branch after some more testing of the wifi functionality.
